### ISSUE TITLE
Synopsis property on 'Search' endpoint bad formatting

### ISSUE THREAD

**Issue by Shompi** [ChrisMichaelPerezSantiago/animeflv#2]
The synopsis property also comes with the 'type' and 'rating' in the beginning.

I hope you can in someway fix this. Thanks!

```javascript
{
synopsis: "Anime 4.7Segunda parte de Sword Art Online: Alicization"
}
```

**Comment by ChrisMichaelPerezSantiago** [comment]
_Hello @Shompi ,_

_The values of the Synopsis and poster properties were fixed in this [commit](https://github.com/ChrisMichaelPerezSantiago/animeflv/commit/e026e0b61283ba6bbe89a7eef87334e3bdfb0c04)._

_I should also mention that the values of the poster property at some API entrypoint were showing me the same issue related to #1._
