### ISSUE TITLE
"poster" property on "Search" Endpoint returns null for every result.

### ISSUE THREAD

**Issue by Shompi** [ChrisMichaelPerezSantiago/animeflv#3]
I hope you can look into this issue, not much to explain really, I think the title is pretty self explanatory.

**Comment by ChrisMichaelPerezSantiago** [comment]
_Hello @Shompi ,_

_Sorry for the delay.
The problem you are presenting is due to CloudFlare_.

_The img element uses `data-cfsrc` to load the img._

**_What is data-cfsrc?_**
> _The data-cfsrc is used by CloudFlare's Mirage feature to lazy-load images to improve website performance._


_The problem with this is that using the animeflv API locally works, but once the API is hosted the official animeflv page uses some cloudflare blocking options allowing hotlinking to be disabled._


_It is a problem that is no longer within my reach, it would be animeflv's decision to enable the hotlinking option, but I don't think it will happen._


_But if you know a way to bypass that restriction, you can let me know._

**Comment by ChrisMichaelPerezSantiago** [comment]
_I already referred to the `data-cfsrc` attribute to load the urls of the images._ 
_You should no longer see `null` on the property `poster`._

_But the problem is still present, due to the use of **CloudFlare**!_ 😢

**Comment by Shompi** [comment]
No problem, thanks you very much for the provisional solution you gave. I don't know about cloudflare so I cant help you with that :( Fell free to close this issue. Again, thanks you!

**Comment by ChrisMichaelPerezSantiago** [comment]
Hi @Shompi ,

I hope you are well.

Verify this issue #4
