### ISSUE TITLE
Don't getting Api responses

### ISSUE THREAD

**Issue by LetrixZ** [ChrisMichaelPerezSantiago/animeflv#7]
Recently, whenever I make a call, I get an 502: BAD_GATEWAY error. In the npm client I get CloudflareError: 1020, Access Denied (Custom Firewall Rules) when making any call.
When I enter the original website, I get two Cloudflare checks. Tried with different networks and devices also.

**Comment by ChrisMichaelPerezSantiago** [comment]
_Yes, I am aware of that situation._

_The vast majority of the time enpoint works only that sometimes the service falls._

_That is because the library that is being used to bypass cloudflare security is having problems, I have to wait for the dev to add the change, for me then update my animeflv library._

_Sorry for the inconvenience!_
